[phases.setup]
nixPkgs = [
  "chromium",
  "chromedriver",
  "nss",
  "freetype",
  "fontconfig",
  "pango",
  "cairo",
  "gdk-pixbuf",
  "gtk3",
  "atk",
  "at-spi2-atk",
  "alsa-lib",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXcursor",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXi",
  "xorg.libXtst",
  "xorg.libXrandr",
  "xorg.libXfixes",
  "xorg.libXrender"
]

